# Generated by Django 3.2.23 on 2024-02-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=70)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_message', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contact_phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
