# Generated by Django 3.2.23 on 2024-02-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='date',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='contactform',
            name='subject',
            field=models.CharField(default='No subject', max_length=200),
        ),
    ]
